// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TelegramLinkCode struct {
	Code      string
	UserID    int32
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	HashPassword string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserIdentity struct {
	ID             int64
	UserID         int32
	Provider       string
	ProviderUserID string
	Username       pgtype.Text
	FirstName      pgtype.Text
	LastName       pgtype.Text
	ChatID         pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
