-- +goose Up
-- +goose StatementBegin

-- Пользователи (web-логин/пароль). Email уникальный.
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT    NOT NULL UNIQUE,
    hash_password TEXT    NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Идентичности пользователя (например, Telegram).
-- Позволяет привязать Telegram к уже созданному web-аккаунту.
CREATE TABLE IF NOT EXISTS user_identities (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    "provider"       TEXT    NOT NULL,      -- 'telegram'
    provider_user_id TEXT    NOT NULL,      -- telegram_user_id строкой

    username         TEXT,
    first_name       TEXT,
    last_name        TEXT,
    chat_id          BIGINT,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_identities_provider UNIQUE (provider, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_identities_user_id
    ON user_identities(user_id);

-- Одноразовые коды для привязки Telegram (web -> bot).
CREATE TABLE IF NOT EXISTS telegram_link_codes (
    code        TEXT PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_telegram_link_codes_user_id
    ON telegram_link_codes(user_id);

CREATE INDEX IF NOT EXISTS idx_telegram_link_codes_expires_at
    ON telegram_link_codes(expires_at);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS telegram_link_codes;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;
-- +goose StatementEnd